export const INCREASE_DECREASE = "INCREASE_DECREASE";
export const ADD_TO_TOTAL = "ADD_TO_TOTAL";
export const PERSENT_OF_FORTUNE = "PERSENT_OF_FORTUNE";
export const ADD_TO_BASKET = "ADD_TO_BASKET"
export const BUY_SELL = "BUY_SELL"
export const FORTUNE_FINISHED = "FORTUNE_FINISHED"
export const USER_SHOPPING_STATUS = "USER_SHOPPING_STATUS"
export const DELETE_TO_BASKET = "DELETE_TO_BASKET"
