const products = {

    productsList: [
        {
            name:"AirPods Pro",
            imgSrc:"https://i.imgur.com/9QtYXwu.jpg",
            unitPrice:249,
            taken:0,
        },
        {
            name:"Nintendo Switch",
            imgSrc:"https://i.imgur.com/NjB1B10.jpg",
            unitPrice:299,
            taken:0,
        },
        {
            name:"PS5",
            imgSrc:"https://i.imgur.com/0GPFIYa.jpg",
            unitPrice:449,
            taken:0,
        },
        {
            name:"Xbox Series X",
            imgSrc:"https://i.imgur.com/B9ePUN9.jpg",
            unitPrice:499,
            taken:0,
        },
        {
            name:"Iphone 14 Pro Max - 1TB",
            imgSrc:"https://i.imgur.com/RDL6SnJ.jpg",
            unitPrice:1599,
            taken:0,
        },
        {
            name:"Samsung S23 Ultra - 1TB",
            imgSrc:"https://i.imgur.com/KyWHsKW.jpg",
            unitPrice:1449,
            taken:0,
        },
        {
            name:"MacBook Pro 14' M2 Max (64GB RAM | 4TB)",
            imgSrc:"https://i.imgur.com/6QjVUZV.jpg",
            unitPrice:4699,
            taken:0,
        },
        {
            name:"2023 Mac Studio M1 Ultra (128GB RAM | 8TB)",
            imgSrc:"https://i.imgur.com/fminWBH.jpg",
            unitPrice:6999,
            taken:0,
        },
        {
            name:"Pro Gaming PC(I9 13900K, RTX 4090, 64GB, 4TB SSD)",
            imgSrc:"https://i.imgur.com/diqWGS7.jpg",
            unitPrice:6950,
            taken:0,
        },
        {
            name:"Razer Blade 14 Top spec (2023)",
            imgSrc:"https://i.imgur.com/C91Spgr.jpg",
            unitPrice:2799,
            taken:0,
        },
        {
            name:"Ipad Air M1 Chip (2023) (256GB)",
            imgSrc:"https://i.imgur.com/6cs5d6D.jpg",
            unitPrice:749,
            taken:0,
        },
        {
            name:"Tesla Bot (Available 2024)",
            imgSrc:"https://i.imgur.com/1zf8Od2.jpg",
            unitPrice:20000,
            taken:0,
        },
        {
            name:"Start your own StartUp",
            imgSrc:"https://i.imgur.com/F8tPuHG.jpg",
            unitPrice:5000000,
            taken:0,
        },
        {
            name:"Open Fast Food Franchise",
            imgSrc:"https://i.imgur.com/LSZCZfI.jpg",
            unitPrice:1500000,
            taken:0,
        },
        {
            name:"Spotify for 80 years",
            imgSrc:"https://i.imgur.com/sgDA4Jc.jpg",
            unitPrice:10600,
            taken:0,
        },
        {
            name:"Entire Steam library (2023 - No discounts)",
            imgSrc:"https://i.imgur.com/6GP748G.jpg",
            unitPrice:728000,
            taken:0,
        },
        {
            name:"Netflix for 80 Years",
            imgSrc:"https://i.imgur.com/zGaCSFJ.jpg",
            unitPrice:16500,
            taken:0,
        },
        {
            name:"Entire production of Nvidia GPUs for 2023",
            imgSrc:"https://i.imgur.com/kjmUU0f.jpg",
            unitPrice:900000000,
            taken:0,
        },
        {
            name:"Influence 1 high ranking politician",
            imgSrc:"https://i.imgur.com/7IB3CLt.jpg",
            unitPrice:2000000,
            taken:0,
        },
        {
            name:"Private Concert with ANY Super Star",
            imgSrc:"https://i.imgur.com/qjQqs0v.jpg",
            unitPrice:1000000,
            taken:0,
        },
        {
            name:"Give 10,000 USD to 5000 people",
            imgSrc:"https://i.imgur.com/NE7sbRU.jpg",
            unitPrice:50000000,
            taken:0,
        },
        {
            name:"LG 88' OLED 8K ThinQ®",
            imgSrc:"https://i.imgur.com/TGGOqdl.jpg",
            unitPrice:19990,
            taken:0,
        },
        {
            name:"Fiat 500",
            imgSrc:"https://i.imgur.com/sk9EP1i.jpg",
            unitPrice:19000,
            taken:0,
        },
        {
            name:"Toyota Camry",
            imgSrc:"https://i.imgur.com/yfQjaS6.jpg",
            unitPrice: 29000,
            taken:0,
        },
        {
            name:"Ford F150 Raptor 2023",
            imgSrc:"https://i.imgur.com/SaSBjQ7.jpg",
            unitPrice:65900,
            taken:0,
        },
        {
            name:"Tesla Model S Plaid",
            imgSrc:"https://i.imgur.com/tfSw6ND.jpg",
            unitPrice:132000,
            taken:0,
        },
        {
            name:"Cybertruck (Tri Motor)",
            imgSrc:"https://i.imgur.com/pHxajOw.jpg",
            unitPrice:70000,
            taken:0,
        },
        {
            name:"Tesla Roadster 2024",
            imgSrc:"https://i.imgur.com/bX4SeTv.jpg",
            unitPrice:200000,
            taken:0,
        },
        {
            name:"Ferrari F8 Tributo",
            imgSrc:"https://i.imgur.com/giumAZC.jpg",
            unitPrice:276000,
            taken:0,
        },
        {
            name:"Lamborghini Aventador SVJ",
            imgSrc:"https://i.imgur.com/NdHxu2p.jpg",
            unitPrice:512000,
            taken:0,
        },
        {
            name:"Bugatti La Voiture Noire",
            imgSrc:"https://i.imgur.com/ULFQYv1.jpg",
            unitPrice:11000000,
            taken:0,
        },
        {
            name:"1000 Acres of land",
            imgSrc:"https://i.imgur.com/4fY8du1.jpg",
            unitPrice:4100000,
            taken:0,
        },
        {
            name:"Private Island, Central America (medium size)",
            imgSrc:"https://i.imgur.com/jtbz2S4.jpg",
            unitPrice:4950000,
            taken:0,
        },
        {
            name:"Eating out for 80 years (4 meals/day)",
            imgSrc:"https://i.imgur.com/CNyhJF3.jpg",
            unitPrice:3100000,
            taken:0,
        },
        {
            name:"Diamond Ring (Tiffany - 1 carat)",
            imgSrc:"https://i.imgur.com/E8sg2YQ.jpg",
            unitPrice:17000,
            taken:0,
        },
        {
            name:"Whisky Macallan Michael Dillon 1926",
            imgSrc:"https://i.imgur.com/momWXBT.jpg",
            unitPrice:1530000,
            taken:0,
        },
        {
            name:"Rolex Oyster",
            imgSrc:"https://i.imgur.com/MUGVZ8i.jpg",
            unitPrice:14000,
            taken:0,
        },
        {
            name:"Les Femmes d’Alger by Picasso",
            imgSrc:"https://i.imgur.com/4a6CDQK.jpg",
            unitPrice:179400000,
            taken:0,
        },
        {
            name:"Monalisa by Leonardo da Vinci (estimate)",
            imgSrc:"https://i.imgur.com/wDo8a6C.jpg",
            unitPrice:869000000,
            taken:0,
        },
        {
            name:"Helicopter Bell 206",
            imgSrc:"https://i.imgur.com/rqZ7IIk.jpg",
            unitPrice:850000,
            taken:0,
        },
        {
            name:"10 plastic surgeries",
            imgSrc:"https://i.imgur.com/yU4EsJj.jpg",
            unitPrice:130000,
            taken:0,
        },
        {
            name:"One week in EVERY country of the planet",
            imgSrc:"https://i.imgur.com/dUxUeHi.jpg",
            unitPrice:1250000,
            taken:0,
        },
        {
            name:"College Education (USA)",
            imgSrc:"https://i.imgur.com/fVNcvTE.jpg",
            unitPrice:190000,
            taken:0,
        },
        {
            name:"NFL Team (Average)",
            imgSrc:"https://i.imgur.com/stpt2ZG.jpg",
            unitPrice:3000000000,
            taken:0,
        },
        {
            name:"NBA Team (Average)",
            imgSrc:"https://i.imgur.com/dr2aFvN.jpg",
            unitPrice:2400000000,
            taken:0,
        },
        {
            name:"F1 Team (Average)",
            imgSrc:"https://i.imgur.com/PKvVuAm.jpg",
            unitPrice:700000000,
            taken:0,
        },

        {
            name:"Jet Gulfstream G450",
            imgSrc:"https://i.imgur.com/QlgwDGF.jpg",
            unitPrice:18000000,
            taken:0,
        },
        {
            name:"M1 Abrams",
            imgSrc:"https://i.imgur.com/jemMZg5.jpg",
            unitPrice:8000000,
            taken:0,
        },
        {
            name:"Produce a Hollywood Movie",
            imgSrc:"https://i.imgur.com/06isRMk.jpg",
            unitPrice:90000000,
            taken:0,
        },{
            name:"Regular Modern Apartment (3 bd, 2 ba)",
            imgSrc:"https://i.imgur.com/8Dd6fiM.jpg",
            unitPrice:420000,
            taken:0,
        },
        {
            name:"Paris Luxury Apartment(3 bd, 3 ba)",
            imgSrc:"https://i.imgur.com/my8vglc.jpg",
            unitPrice:3200000,
            taken:0,
        },
        {
            name:"L.A Home (5bd, 6ba)",
            imgSrc:"https://i.imgur.com/ypjjQYX.jpg",
            unitPrice:6000000,
            taken:0,
        },
        {
            name:"L.A Mega Mansion (8 bd, 20 ba)",
            imgSrc:"https://i.imgur.com/iGbwSSM.jpg",
            unitPrice:52000000,
            taken:0,
        },
        {
            name:"Modern Building (35 condos + 10 Offices)",
            imgSrc:"https://i.imgur.com/j2JS3Us.jpg",
            unitPrice:12000000,
            taken:0,
        },
        {
            name:"Sailboat",
            imgSrc:"https://i.imgur.com/jsbtkG7.jpg",
            unitPrice:130000,
            taken:0,
        },
        {
            name:"Mega Yatch",
            imgSrc:"https://i.imgur.com/DGX1I5F.jpg",
            unitPrice:300000000,
            taken:0,
        },

        
    ],
    totalPrice: 217000000000,
    persent:0
}


export default products;
    