const products = {

    productslist: [
        {
            name:"AirPods Pro",
            imagesrc:"https://i.imgur.com/9QtYXwu.jpg",
            birimfiyat:249,
            alınan:0,
        },
        {
            name:"Nintendo Switch",
            imagesrc:"https://i.imgur.com/NjB1B10.jpg",
            birimfiyat:299,
            alınan:0,
        },
        {
            name:"PS5",
            imagesrc:"https://i.imgur.com/0GPFIYa.jpg",
            birimfiyat:449,
            alınan:0,
        },
        {
            name:"Xbox Series X",
            imagesrc:"https://i.imgur.com/B9ePUN9.jpg",
            birimfiyat:499,
            alınan:0,
        },
        {
            name:"Iphone 14 Pro Max - 1TB",
            imagesrc:"https://i.imgur.com/RDL6SnJ.jpg",
            birimfiyat:1599,
            alınan:0,
        },
        {
            name:"Samsung S23 Ultra - 1TB",
            imagesrc:"https://i.imgur.com/KyWHsKW.jpg",
            birimfiyat:1449,
            alınan:0,
        },
        {
            name:"MacBook Pro 14' M2 Max (64GB RAM | 4TB)",
            imagesrc:"https://i.imgur.com/6QjVUZV.jpg",
            birimfiyat:4699,
            alınan:0,
        },
        {
            name:"2023 Mac Studio M1 Ultra (128GB RAM | 8TB)",
            imagesrc:"https://i.imgur.com/fminWBH.jpg",
            birimfiyat:6999,
            alınan:0,
        },
        {
            name:"Pro Gaming PC(I9 13900K, RTX 4090, 64GB, 4TB SSD)",
            imagesrc:"https://i.imgur.com/diqWGS7.jpg",
            birimfiyat:6950,
            alınan:0,
        },
        {
            name:"Razer Blade 14 Top spec (2023)",
            imagesrc:"https://i.imgur.com/C91Spgr.jpg",
            birimfiyat:2799,
            alınan:0,
        },
        {
            name:"Ipad Air M1 Chip (2023) (256GB)",
            imagesrc:"https://i.imgur.com/6cs5d6D.jpg",
            birimfiyat:749,
            alınan:0,
        },
        {
            name:"Tesla Bot (Available 2024)",
            imagesrc:"https://i.imgur.com/1zf8Od2.jpg",
            birimfiyat:20000,
            alınan:0,
        },
        {
            name:"Start your own StartUp",
            imagesrc:"https://i.imgur.com/F8tPuHG.jpg",
            birimfiyat:5000000,
            alınan:0,
        },
        {
            name:"Open Fast Food Franchise",
            imagesrc:"https://i.imgur.com/LSZCZfI.jpg",
            birimfiyat:1500000,
            alınan:0,
        },
        {
            name:"Spotify for 80 years",
            imagesrc:"https://i.imgur.com/sgDA4Jc.jpg",
            birimfiyat:10600,
            alınan:0,
        },
        {
            name:"Entire Steam library (2023 - No discounts)",
            imagesrc:"https://i.imgur.com/6GP748G.jpg",
            birimfiyat:728000,
            alınan:0,
        },
        {
            name:"Netflix for 80 Years",
            imagesrc:"https://i.imgur.com/zGaCSFJ.jpg",
            birimfiyat:16500,
            alınan:0,
        },
        {
            name:"Entire production of Nvidia GPUs for 2023",
            imagesrc:"https://i.imgur.com/kjmUU0f.jpg",
            birimfiyat:900000000,
            alınan:0,
        },
        {
            name:"Influence 1 high ranking politician",
            imagesrc:"https://i.imgur.com/7IB3CLt.jpg",
            birimfiyat:2000000,
            alınan:0,
        },
        {
            name:"Private Concert with ANY Super Star",
            imagesrc:"https://i.imgur.com/qjQqs0v.jpg",
            birimfiyat:1000000,
            alınan:0,
        },
        {
            name:"Give 10,000 USD to 5000 people",
            imagesrc:"https://i.imgur.com/NE7sbRU.jpg",
            birimfiyat:50000000,
            alınan:0,
        },
        {
            name:"LG 88' OLED 8K ThinQ®",
            imagesrc:"https://i.imgur.com/TGGOqdl.jpg",
            birimfiyat:19990,
            alınan:0,
        },
        {
            name:"Fiat 500",
            imagesrc:"https://i.imgur.com/sk9EP1i.jpg",
            birimfiyat:19000,
            alınan:0,
        },
        {
            name:"Toyota Camry",
            imagesrc:"https://i.imgur.com/yfQjaS6.jpg",
            birimfiyat: 29000,
            alınan:0,
        },
        {
            name:"Ford F150 Raptor 2023",
            imagesrc:"https://i.imgur.com/SaSBjQ7.jpg",
            birimfiyat:65900,
            alınan:0,
        },
        {
            name:"Tesla Model S Plaid",
            imagesrc:"https://i.imgur.com/tfSw6ND.jpg",
            birimfiyat:132000,
            alınan:0,
        },
        {
            name:"Cybertruck (Tri Motor)",
            imagesrc:"https://i.imgur.com/pHxajOw.jpg",
            birimfiyat:70000,
            alınan:0,
        },
        {
            name:"Tesla Roadster 2024",
            imagesrc:"https://i.imgur.com/bX4SeTv.jpg",
            birimfiyat:200000,
            alınan:0,
        },
        {
            name:"Ferrari F8 Tributo",
            imagesrc:"https://i.imgur.com/giumAZC.jpg",
            birimfiyat:276000,
            alınan:0,
        },
        {
            name:"Lamborghini Aventador SVJ",
            imagesrc:"https://i.imgur.com/NdHxu2p.jpg",
            birimfiyat:512000,
            alınan:0,
        },
        {
            name:"Bugatti La Voiture Noire",
            imagesrc:"https://i.imgur.com/ULFQYv1.jpg",
            birimfiyat:11000000,
            alınan:0,
        },
        {
            name:"1000 Acres of land",
            imagesrc:"https://i.imgur.com/4fY8du1.jpg",
            birimfiyat:4100000,
            alınan:0,
        },
        {
            name:"Private Island, Central America (medium size)",
            imagesrc:"https://i.imgur.com/jtbz2S4.jpg",
            birimfiyat:4950000,
            alınan:0,
        },
        {
            name:"Eating out for 80 years (4 meals/day)",
            imagesrc:"https://i.imgur.com/CNyhJF3.jpg",
            birimfiyat:3100000,
            alınan:0,
        },
        {
            name:"Diamond Ring (Tiffany - 1 carat)",
            imagesrc:"https://i.imgur.com/E8sg2YQ.jpg",
            birimfiyat:17000,
            alınan:0,
        },
        {
            name:"Whisky Macallan Michael Dillon 1926",
            imagesrc:"https://i.imgur.com/momWXBT.jpg",
            birimfiyat:1530000,
            alınan:0,
        },
        {
            name:"Rolex Oyster",
            imagesrc:"https://i.imgur.com/MUGVZ8i.jpg",
            birimfiyat:14000,
            alınan:0,
        },
        {
            name:"Les Femmes d’Alger by Picasso",
            imagesrc:"https://i.imgur.com/4a6CDQK.jpg",
            birimfiyat:179400000,
            alınan:0,
        },
        {
            name:"Monalisa by Leonardo da Vinci (estimate)",
            imagesrc:"https://i.imgur.com/wDo8a6C.jpg",
            birimfiyat:869000000,
            alınan:0,
        },
        {
            name:"Helicopter Bell 206",
            imagesrc:"https://i.imgur.com/rqZ7IIk.jpg",
            birimfiyat:850000,
            alınan:0,
        },
        {
            name:"10 plastic surgeries",
            imagesrc:"https://i.imgur.com/yU4EsJj.jpg",
            birimfiyat:130000,
            alınan:0,
        },
        {
            name:"One week in EVERY country of the planet",
            imagesrc:"https://i.imgur.com/dUxUeHi.jpg",
            birimfiyat:1250000,
            alınan:0,
        },
        {
            name:"College Education (USA)",
            imagesrc:"https://i.imgur.com/fVNcvTE.jpg",
            birimfiyat:190000,
            alınan:0,
        },
        {
            name:"NFL Team (Average)",
            imagesrc:"https://i.imgur.com/stpt2ZG.jpg",
            birimfiyat:3000000000,
            alınan:0,
        },
        {
            name:"NBA Team (Average)",
            imagesrc:"https://i.imgur.com/dr2aFvN.jpg",
            birimfiyat:2400000000,
            alınan:0,
        },
        {
            name:"F1 Team (Average)",
            imagesrc:"https://i.imgur.com/PKvVuAm.jpg",
            birimfiyat:700000000,
            alınan:0,
        },

        {
            name:"Jet Gulfstream G450",
            imagesrc:"https://i.imgur.com/QlgwDGF.jpg",
            birimfiyat:18000000,
            alınan:0,
        },
        {
            name:"M1 Abrams",
            imagesrc:"https://i.imgur.com/jemMZg5.jpg",
            birimfiyat:8000000,
            alınan:0,
        },
        {
            name:"Produce a Hollywood Movie",
            imagesrc:"https://i.imgur.com/06isRMk.jpg",
            birimfiyat:90000000,
            alınan:0,
        },{
            name:"Regular Modern Apartment (3 bd, 2 ba)",
            imagesrc:"https://i.imgur.com/8Dd6fiM.jpg",
            birimfiyat:420000,
            alınan:0,
        },
        {
            name:"Paris Luxury Apartment(3 bd, 3 ba)",
            imagesrc:"https://i.imgur.com/my8vglc.jpg",
            birimfiyat:3200000,
            alınan:0,
        },
        {
            name:"L.A Home (5bd, 6ba)",
            imagesrc:"https://i.imgur.com/ypjjQYX.jpg",
            birimfiyat:6000000,
            alınan:0,
        },
        {
            name:"L.A Mega Mansion (8 bd, 20 ba)",
            imagesrc:"https://i.imgur.com/iGbwSSM.jpg",
            birimfiyat:52000000,
            alınan:0,
        },
        {
            name:"Modern Building (35 condos + 10 Offices)",
            imagesrc:"https://i.imgur.com/j2JS3Us.jpg",
            birimfiyat:12000000,
            alınan:0,
        },
        {
            name:"Sailboat",
            imagesrc:"https://i.imgur.com/jsbtkG7.jpg",
            birimfiyat:130000,
            alınan:0,
        },
        {
            name:"Mega Yatch",
            imagesrc:"https://i.imgur.com/DGX1I5F.jpg",
            birimfiyat:300000000,
            alınan:0,
        },

        
    ],
    forreceipt:[],
    totalprice: 217000000000,
    persent:0
}


export default products;
    